export const FETCH_USER = 'FETCH_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_AUTH_TOKEN = 'FETCH_AUTH_TOKEN';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const ZERO_CHANNELS = 'ZERO_CHANNELS';
export const LOADING_CHANGE_USER_NAME = 'LOADING_CHANGE_USER_NAME';
export const LOADING_CHANGE_AVATAR = 'LOADING_CHANGE_AVATAR';
export const LOADING_CREATE_CHANNEL = 'LOADING_CREATE_CHANNEL';
export const LOADING_DELETE_CHANNEL = 'LOADING_DELETE_CHANNEL';
export const LOADING_ACTIVE_CHANNEL = 'LOADING_ACTIVE_CHANNEL';
export const LOADING_EDIT_CHANNEL = 'LOADING_EDIT_CHANNEL';
export const LOADING_LOGIN = 'LOADING_LOGIN';
export const LOADING_REGISTER = 'LOADING_REGISTER';


