export const LOGGED_USER = 'LOGGED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_AUTH_TOKEN = 'FETCH_AUTH_TOKEN';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const ACTIVE_CHANNEL = 'ACTIVE_CHANNEL';

