export const FETCH_USER = 'FETCH_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_AUTH_TOKEN = 'FETCH_AUTH_TOKEN';
export const FETCH_CHANNELS = 'FETCH_CHANNELS';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

